
## Numpy - Numerical Python
1. Numpy Arrays

In [1]:
#creating 1-D Arrays
import numpy as np

arr1 = np.array([1,2,3,4,5])
print(arr1)
type(arr1)

[1 2 3 4 5]


numpy.ndarray

In [2]:
arr1.shape

(5,)

In [3]:
# creating 2x2 matrix
a = np.array([[1,0],[2,4]])
print(a)
print("shape of array : ")
a.shape

[[1 0]
 [2 4]]
shape of array : 


(2, 2)

In [4]:
#Mentioning Datatype
c = np.array([[1,2,3],[4,5,6],[7,8,9]], dtype = float)
print(c)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


# Initial Placeholders in NumPy Arrays


In [5]:
#create a numpy array of Zeros

x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [6]:
# create a numpy arrays of ones

y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [7]:
# create an array of a particular value
z = np.full((5,4),5)  #((row,col), placeholder value)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


# Identity Matrix

In [8]:
#create an identity matrix
id = np.eye(3)  #(shape of array :Int)
print(id)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [9]:
#create a numpy array with random values

r = np.random.random((3,4))
print(r)
#Note: All the values will be btw 0 and 1

[[0.22469441 0.08738626 0.09006156 0.65160869]
 [0.48067781 0.98942507 0.95992725 0.11878911]
 [0.04512414 0.95336949 0.38574897 0.42319341]]


In [10]:
 # create Integer values array wihtin specific Range:
 c = np.random.randint(1,9,(5,10))
 print(c)

[[4 5 2 3 5 3 8 6 5 2]
 [1 4 4 5 2 3 1 2 5 4]
 [3 3 8 5 4 3 6 1 7 5]
 [5 4 1 3 1 3 2 2 3 4]
 [6 2 4 4 6 7 1 6 8 3]]


In [11]:
#array of eveny spaced vlaue

d = np.linspace(10,30,6)  #6 means --> specifying the number of values required
print(d)

[10. 14. 18. 22. 26. 30.]


In [12]:
#array of evenly spaced values - > specifying the step
e = np.arange(10,30,5)
print(e)

[10 15 20 25]


Convert a List to NumPy Array


In [13]:
list1 = [10,20,30,40,50]
print("Datatype of List: ", type(list1))
np_array = np.asarray(list1)
print(np_array)
print("DataType of Array: ", type(np_array))

Datatype of List:  <class 'list'>
[10 20 30 40 50]
DataType of Array:  <class 'numpy.ndarray'>


# Analyzing a NumPy Array

In [14]:
np_arr = np.random.randint(10,90,(5,5))
print(np_arr)

[[57 13 16 51 86]
 [54 76 14 60 61]
 [43 44 24 75 16]
 [59 77 72 14 21]
 [18 38 86 38 29]]


In [15]:
#Array Dimension
print(np_arr.shape)

(5, 5)


In [16]:
#Number of dimensions
print(np_arr.ndim)   #ndim -> N-Dimensional
#output = 2, That means it is a  2-D array

2


In [17]:
#checking no. of ele in the array
print(np_arr.size)

25


In [18]:
#cheking datatype of values in the array
print(np_arr.dtype)

int32


## *Mathematical Operation on a Array*

In [19]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))


In [20]:
# Addition
print(a+b)
#Subtraction
print(a-b)
#Multiplication
print(a * b)
#dividion
print(a / b)

[[17 28 17]
 [21 20 19]
 [16 20 27]]
[[-13 -10  -7]
 [ -3  -6 -13]
 [-14  -4  -9]]
[[ 30 171  60]
 [108  91  48]
 [ 15  96 162]]
[[0.13333333 0.47368421 0.41666667]
 [0.75       0.53846154 0.1875    ]
 [0.06666667 0.66666667 0.5       ]]


In [21]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))


In [22]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[12 11 24]
 [12 18 17]
 [27 18 20]]
[[ -8  -9 -14]
 [-10  -4  -7]
 [ -9 -16 -10]]
[[ 20  10  95]
 [ 11  77  60]
 [162  17  75]]
[[0.2        0.1        0.26315789]
 [0.09090909 0.63636364 0.41666667]
 [0.5        0.05882353 0.33333333]]


# Array Manipulation

In [23]:
array = np.random.randint(0,10,(2,3))
print(array)

print("Shape: ",array.shape)


[[1 9 1]
 [9 2 5]]
Shape:  (2, 3)


In [24]:
#Transpose
trans = np.transpose(array)
print(trans)
print("Shape: ", trans.shape)


# 2nd way to find Transpose
#trans2 = array.T
#print(trans2)



[[1 9]
 [9 2]
 [1 5]]
Shape:  (3, 2)


In [25]:
# Re-shaping Array
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)


[[3 1 1]
 [7 8 9]]
(2, 3)


In [26]:
b = a.reshape(3,2)
print(b)

[[3 1]
 [1 7]
 [8 9]]
