In [121]:
%pip install word2number

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [122]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import linear_model
from word2number import w2n

Ques :

Given these home prices find out price of a home that has,
 - 3000 sqr ft area, 3 bedrooms, 40 year old
 - 2500 sqr ft area, 4 bedrooms, 5 year old

 price = m1 * area + m2 * bedrooms + m3 * age + b

In [123]:
df = pd.read_csv('homeprices.csv')
df.head(10)

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [124]:
med = df.bedrooms.median()

In [125]:
df.bedrooms.fillna(med, inplace=True)

C:\Users\Harpreet singh\AppData\Local\Temp\ipykernel_22772\1222233713.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.bedrooms.fillna(med, inplace=True)


In [126]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [127]:
reg = linear_model.LinearRegression()

In [128]:
reg.fit(df[['area', 'bedrooms', 'age']], df['price'])

LinearRegression()

In [129]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [130]:
reg.intercept_

221323.0018654043

In [131]:
reg.predict([[3000, 3, 40]])

c:\Users\Harpreet singh\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([498408.25158031])

In [132]:
reg.predict([[2500, 4.0, 5]])

c:\Users\Harpreet singh\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([578876.03748933])

<h2>Practice Exercise</h2>

In exercise folder (same level as this notebook on github) there is hiring.csv. This file contains hiring statics for a firm such as experience of candidate, his written test score and personal interview score. Based on these 3 factors, HR will decide the salary. Given this data, you need to build a machine learning model for HR department that can help them decide salaries for future candidates. Using this predict salaries for following candidates,

- 2 yr experience, 9 test score, 6 interview score

- 12 yr experience, 10 test score, 10 interview score

In [133]:
data = pd.read_csv('hiring.csv')

In [134]:
data

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [150]:
import math
median_value = math.floor(data['test_score(out of 10)'].median())
median_value

8

In [151]:
# data['test_score(out of 10)'].fillna(median_value, inplace=True)

data['test_score(out of 10)'] = data['test_score(out of 10)'].fillna(median_value)

In [152]:
data.head(10)

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    8.0                           7      72000
7          11                    7.0                           8      80000

In [153]:
data['experience'] = data['experience'].fillna('zero')

In [154]:
data

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    8.0                           7      72000
7          11                    7.0                           8      80000

In [155]:
def safe_word_to_num(val):
    try:
        if isinstance(val, str):  # Only apply word_to_num if it's a string
            return w2n.word_to_num(val)
        else:
            return val  # Return the value as it is if it's not a string
    except ValueError:
        return np.nan  # In case of conversion error, return NaN

# Apply the function to the 'experience' column
data['experience'] = data['experience'].apply(safe_word_to_num)

# Display the updated DataFrame
data

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    8.0                           7      72000
7          11                    7.0                           8      80000

In [156]:
reg = linear_model.LinearRegression()

In [157]:
reg.fit(data[['experience', 'test_score(out of 10)', 'interview_score(out of 10)']], data['salary($)'])

LinearRegression()

In [158]:
reg.predict([[2, 9, 6]])

c:\Users\Harpreet singh\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([53205.96797671])

In [159]:
reg.predict([[12, 10, 10]])

c:\Users\Harpreet singh\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([92002.18340611])